seed: 42
test_size: 0.25
max_features: 0.75
criterion: gini
splitter: best
max_depth: 20
min_samples_split: 10
min_samples_leaf: 5
random_state: 42
n_estimators: 250
max_samples: 0.75
bootstrap: false
bootstrap_features: false
oob_score: false
warm_start: false
verbose: 1
